services:
  - type: web
    name: ces-price-telegram-bot
    env: node
    plan: free
    buildCommand: yarn install
    startCommand: yarn start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CMC_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false